config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  get 'welcome/index'

  resources :articles
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show]

  # this is executed when url patter is /articles/new
  def new
  end

  # this is executed when url pattern is /articles/
  def index
    @articles = Article.all
  end

  # this is executed when url pattern is /articles/  & method: POST
  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = "Article created successfully."
      redirect_to @article
    else
      flash[:notice] = "Error creating Article."
    end
  end

  # this is executed when url pattern is /articles/{id}/edit
  def edit
  end

  # this is executed when url pattern is /articles/{id} & method: PUT or PATCH
  def update
    if @article.update(article_params)
      flash[:notice] = "Article updated successfully."
      redirect_to @article
    else
      flash[:notice] = "Error updating Article."
      render 'edit'
    end
  end

  # this is executed when url pattern is /articles/{id} & method: GET
  def show
  end

  # this is executed when url pattern is /articles/{id} & method: DELETE
  def destroy
    if @article.destroy
      flash[:notice] = "Article #{@article.title} destroyed successfully."
    end
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

  private
  def set_article
    # 
    @article = Article.find(params[:id])
  end

end


# Once the controller executes a method in this controller, it the renders the view lying in the folder name same as
# that of the controller and the filename same as that of the method.
# for eg. articles_controller#new once this is executed, it automatically renders the new.html.erb view lying in the
# articles folder of views folder hierarchy until and unless code to render other view is provided explicitly.

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<%= form_for @article, url: article_path(@article), html: {class: 'form-group'}, method: :patch do |f| %>
   <table>
    <tr>
      <td><%= f.label :title %></td>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
        <td><%= f.label :text %></td>
        <td><%= f.text_area :text %></td>
    </tr>
    <tr><td><%= f.submit %> </td></tr>
  </table>
<% end %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Details</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article.id) %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure? '} %></td>
      </tr>
  <% end %>
</table>


<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
          <p class="alert alert-success"><%= flash[:notice] %></p>
      <% end %>
      <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<p>Please click on the following link to proceed:</p>

<ul>
  <li><%= link_to 'List all articles', controller: 'articles' %></li>
  <li><%= link_to 'Create new article', controller: 'articles', action: 'new' %></li>

</ul>